image:
  file: .gitpod.Dockerfile
tasks:
  - init: sbt compile
    command: sbt ~run

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
#ports:
#  - port: 3000
#    onOpen: open-preview
